### PR TITLE
Hl7 13 am get file endpoint route

### PR DESCRIPTION
**Pull request by amathew8**
Ticket: https://jira.amida.com/browse/HL7-13

## What does this ticket do?
- Adds endpoint to retrieve uploaded HL7 files
- Adds unit test for retrieval ruction
- Also removed the date from filename in order to retrieve filenames without having to know timestamp

## How to Test:
 -  Send a GET request from postman with the filename in the request URL
 - Make sure the contents of the file are outputted 
- Make sure `yarn test` passes and there are no linting errors. 

## NEW TICKET

So I decided to create a new ticket to update the endpoint to what Perry said about returning an Object as opposed to just the raw HL7 file. So check that out as well

New Ticket=> https://jira.amida.com/browse/HL7-19

### CODE REVIEW

**Comment by Perry5** [comment]
This branch was created off `hl7-2-AJP-upload-file-to-server` so it contains the un-merged changes in that brach. This was done because @amathew8 needed the POST function working before he could test his GET endpoint. 

So we might want to review and merge this PR first:
https://github.com/amida-tech/hl7-telescoper-api-server/pull/2

**Review by Perry5 — COMMENTED** [review]
Code looks good- this seems like the first part of the ticket. 

Right now we just return the Raw message as a text. We need to return an object which contains the file name, id, and a list of all the messages. We can either create a separate ticket for that and merge this in (which would be my suggestion). Or add that in here. 

Seems like what we want to return should look something like this
```
{
  filename: 'filename',
  id: fileUUID,
  messages: [
    {
      rawMessage: 'the raw string of the hl7 message goes here',
    },
    ...moreMessages,
  ],
}
```

Up to you @amathew8

**Comment by amathew8** [comment]
> Code looks good- this seems like the first part of the ticket.
> 
> Right now we just return the Raw message as a text. We need to return an object which contains the file name, id, and a list of all the messages. We can either create a separate ticket for that and merge this in (which would be my suggestion). Or add that in here.
> 
> Seems like what we want to return should look something like this
> 
> ```
> {
>   filename: 'filename',
>   id: fileUUID,
>   messages: [
>     {
>       rawMessage: 'the raw string of the hl7 message goes here',
>     },
>     ...moreMessages,
>   ],
> }
> ```
> 
> Up to you @amathew8

**Comment by amathew8** [comment]
So I decided to create a new ticket to update the endpoint to what Perry said about returning an Object as opposed to just the raw HL7 file. 


New Ticket=>   https://jira.amida.com/browse/HL7-19

**Review by Perry5 — APPROVED** [review]
Approving this since the additional work has been done on a new branch

**Review by orndorffgrant — COMMENTED** [review]
going to close this since its been replaced by #7

**Pull request closed without merging**
